global:
  registryOverride: "registry.redhat.io/rhacm2"
  imageOverrides:
    governance_policy_propagator: "governance-policy-propagator-rhel9@sha256:4bcb10f7d90c432b5264e07be2644474155fb4959999e1467b98e0232682895e"
    governance_policy_addon_controller: "acm-governance-policy-addon-controller-rhel9@sha256:6278eec7d7180aa9a767bd875221857cac66fdbb62f2fa506d63cc70c4e716cf"
    config_policy_controller: "config-policy-controller-rhel9@sha256:bb69be77b2205cd055e10bc4bcebe44186beff74b4c99835206bfe6045313e06"
    governance_policy_framework_addon: "acm-governance-policy-framework-addon-rhel9@sha256:14678c731799cd03e21ffcb7c2617781de1f80275017556724de8acdc7e213d3"
    klusterlet_addon_controller: "klusterlet-addon-controller-rhel9@sha256:ad7f30c61bb11c0d32686e75b01f3b286a1fb06edd8d2ef6a9e2d924fba2b565"
  namespace: multicluster-engine
  pullSecret: open-cluster-management-image-pull-credentials
  cma:
    defaultConfig:
      name: addon-hosted-config
      namespace: multicluster-engine
