apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: spoke
  annotations:
    import.open-cluster-management.io/klusterlet-deploy-mode: Hosted
    import.open-cluster-management.io/hosting-cluster-name: local-cluster
    addon.open-cluster-management.io/enable-hosted-mode-addons: "true"
    open-cluster-management/created-via: other
  labels:
    cluster.open-cluster-management.io/clusterset: default
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
