apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: backplane-operator
  name: multicluster-engine-operator
  namespace: multicluster-engine
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      control-plane: backplane-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        control-plane: backplane-operator
        ocm-antiaffinity-selector: backplane-operator
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - backplane-operator
              topologyKey: topology.kubernetes.io/zone
            weight: 70
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - backplane-operator
              topologyKey: kubernetes.io/hostname
            weight: 35
      containers:
      - args:
        - --leader-elect
        command:
        - /app/backplane-operator
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: OPERAND_IMAGE_APISERVER_NETWORK_PROXY
          value: quay.io/stolostron/apiserver-network-proxy@sha256
        - name: OPERAND_IMAGE_ASSISTED_IMAGE_SERVICE
          value: quay.io/stolostron/assisted-image-service@sha256
        - name: OPERAND_IMAGE_ASSISTED_INSTALLER
          value: quay.io/stolostron/assisted-installer@sha256
        - name: OPERAND_IMAGE_ASSISTED_INSTALLER_AGENT
          value: quay.io/stolostron/assisted-installer-agent@sha256
        - name: OPERAND_IMAGE_ASSISTED_INSTALLER_CONTROLLER
          value: quay.io/stolostron/assisted-installer-controller@sha256
        - name: OPERAND_IMAGE_ASSISTED_SERVICE_9
          value: quay.io/stolostron/assisted-service@sha256
        - name: OPERAND_IMAGE_ASSISTED_SERVICE_8
          value: quay.io/stolostron/assisted-service-el8@sha256
        - name: OPERAND_IMAGE_AWS_ENCRYPTION_PROVIDER
          value: quay.io/stolostron/aws-encryption-provider@sha256
        - name: OPERAND_IMAGE_BACKPLANE_MUST_GATHER
          value: quay.io/stolostron/backplane-must-gather@sha256
        - name: OPERAND_IMAGE_BACKPLANE_OPERATOR_TEST
          value: quay.io/stolostron/backplane-operator-test@sha256
        - name: OPERAND_IMAGE_CLUSTER_API
          value: quay.io/stolostron/cluster-api@sha256
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_AWS
          value: quay.io/stolostron/cluster-api-aws-controller@sha256
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_AGENT
          value: quay.io/stolostron/cluster-api-provider-agent@sha256
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_AZURE
          value: quay.io/stolostron/cluster-api-provider-azure@sha256
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_KUBEVIRT
          value: quay.io/stolostron/cluster-api-provider-kubevirt@sha256
        - name: OPERAND_IMAGE_CLUSTER_CURATOR_CONTROLLER
          value: quay.io/stolostron/cluster-curator-controller@sha256
        - name: OPERAND_IMAGE_CLUSTER_IMAGE_SET_CONTROLLER
          value: quay.io/stolostron/cluster-image-set-controller@sha256
        - name: OPERAND_IMAGE_CLUSTER_PROXY
          value: quay.io/stolostron/cluster-proxy@sha256
        - name: OPERAND_IMAGE_CLUSTER_PROXY_ADDON
          value: quay.io/stolostron/cluster-proxy-addon@sha256
        - name: OPERAND_IMAGE_CLUSTERCLAIMS_CONTROLLER
          value: quay.io/stolostron/clusterclaims-controller@sha256
        - name: OPERAND_IMAGE_CONSOLE_MCE
          value: quay.io/stolostron/console-mce@sha256
        - name: OPERAND_IMAGE_DISCOVERY_OPERATOR
          value: quay.io/stolostron/discovery-operator@sha256
        - name: OPERAND_IMAGE_DISCOVERY_OPERATOR_TESTS
          value: quay.io/stolostron/discovery-operator-tests@sha256
        - name: OPERAND_IMAGE_DISCOVERY_TESTSERVER
          value: quay.io/stolostron/discovery-testserver@sha256
        - name: OPERAND_IMAGE_FOUNDATION_E2E
          value: quay.io/stolostron/foundation-e2e@sha256
        - name: OPERAND_IMAGE_HELLOPROW_GO
          value: quay.io/stolostron/helloprow-go@sha256
        - name: OPERAND_IMAGE_HELLOWORLD
          value: quay.io/stolostron/helloworld@sha256
        - name: OPERAND_IMAGE_OPENSHIFT_HIVE
          value: quay.io/stolostron/hive@sha256
        - name: OPERAND_IMAGE_HYPERSHIFT_ADDON_OPERATOR_CANARY_TEST
          value: quay.io/stolostron/hypershift-addon-operator-canary-test@sha256
        - name: OPERAND_IMAGE_HYPERSHIFT_OPERATOR
          value: {{ .Values.images.overrides.hypershift_operator }}
        - name: OPERAND_IMAGE_IMAGE_BASED_INSTALL_OPERATOR
          value: quay.io/stolostron/image-based-install-operator@sha256
        - name: OPERAND_IMAGE_MANAGED_SERVICEACCOUNT
          value: quay.io/stolostron/managed-serviceaccount@sha256
        - name: OPERAND_IMAGE_MANAGED_SERVICEACCOUNT_E2E
          value: quay.io/stolostron/managed-serviceaccount-e2e@sha256
        - name: OPERAND_IMAGE_POSTGRESQL_12
          value: quay.io/stolostron/postgresql-12-centos7@sha256
        - name: OPERAND_IMAGE_PROVIDER_CREDENTIAL_CONTROLLER
          value: quay.io/stolostron/provider-credential-controller@sha256
        - name: OPERAND_IMAGE_ADDON_MANAGER
          value: {{ .Values.images.overrides.addon_manager }}
        - name: OPERAND_IMAGE_BACKPLANE_OPERATOR
          value: {{ .Values.images.overrides.backplane_operator }}
        - name: OPERAND_IMAGE_HYPERSHIFT_ADDON_OPERATOR
          value: {{ .Values.images.overrides.hypershift_addon_operator }}
        - name: OPERAND_IMAGE_MANAGEDCLUSTER_IMPORT_CONTROLLER
          value: {{ .Values.images.overrides.managedcluster_import_controller }}
        - name: OPERAND_IMAGE_MULTICLOUD_MANAGER
          value: {{ .Values.images.overrides.multicloud_manager }}
        - name: OPERAND_IMAGE_PLACEMENT
          value: {{ .Values.images.overrides.placement }}
        - name: OPERAND_IMAGE_REGISTRATION
          value: {{ .Values.images.overrides.registration }}
        - name: OPERAND_IMAGE_REGISTRATION_OPERATOR
          value: {{ .Values.images.overrides.registration_operator }}
        - name: OPERAND_IMAGE_WORK
          value: {{ .Values.images.overrides.work }}
        - name: OPERAND_IMAGE_KUBE_RBAC_PROXY_MCE
          value: {{ .Values.images.overrides.kube_rbac_proxy_mce }}
        - name: OPERAND_IMAGE_CLUSTERLIFECYCLE_STATE_METRICS
          value: {{ .Values.images.overrides.clusterlifecycle_state_metrics }}
        - name: OPERATOR_VERSION
          value: {{ .Chart.AppVersion }}
        - name: OPERATOR_PACKAGE
          value: multicluster-engine
        - name: OPERATOR_CONDITION_NAME
          value: multicluster-engine.v{{ .Chart.AppVersion }}
        image: {{ .Values.images.overrides.backplane_operator }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: backplane-operator
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: multicluster-engine-operator
      serviceAccountName: multicluster-engine-operator
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: multicluster-engine-operator-webhook
