apiVersion: v1
kind: Service
metadata:
  annotations:
  name: multicluster-engine-operator-webhook-service
  namespace: multicluster-engine
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: backplane-operator
  sessionAffinity: None
  type: ClusterIP

